#on peut le faire avec les pojo
spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: data
          uri: lb://MONITOR-DATA
          predicates:
            - Path=/data/**
          filters:
            - RewritePath=/data/(?<segment>.*), /$\{segment}
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${AUTH_URI:http://test-inter.proximo.africa:9007/auth/realms/atps}
            user-name-attribute: preferred_username
        registration:
          keycloak:
            client-id: ${AUTH_CLIENT_ID:monitor}
            client-secret: ${AUTH_SECRET:015d6586-74d3-4f69-b3b9-037af74b4589}
